version: "3.2"
services:
  apache-php:
    container_name: apache-php
    build:
      context: apache
    links:
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./../src/
        target: /var/www/html
      - type: bind
        source: ./apache/password_manager.conf
        target: /etc/apache2/sites-enabled/password_manager.conf
    networks:
      password_manager:
        ipv4_address: 172.22.1.3
    depends_on:
      - mysql
      - test-smtp

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: password_manager_db
        target: /var/lib/mysql
      - type: bind
        source: ./sql/password_manager.sql
        target: /docker-entrypoint-initdb.d/00-init.sql
      - type: bind
        source: ./sql/pregen_junk.sql
        target: /docker-entrypoint-initdb.d/01-junk.sql
    environment:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_USER: password_manager
        MYSQL_PASSWORD: admin123123
        MYSQL_DATABASE: password_manager
    networks:
      password_manager:
        ipv4_address: 172.22.1.4

  test-smtp:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      password_manager:
        ipv4_address: 172.22.1.5
    restart: always

  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/standalone-chrome:96.0
#    ports:
#      - 4444:4444
    networks:
      password_manager:
        ipv4_address: 172.22.1.6


  selenium-client:
    container_name: selenium-client
    image: maven:3.6.0-jdk-8-alpine
#    entrypoint: ["tail","-f","/dev/null"]
    entrypoint: ["/bin/bash", "-c", "cd /opt/app; mvn test"]
    expose:
      - "5005"
    volumes:
      - ../testing:/opt/app
      - maven_cache:/root/.m2
    networks:
      password_manager:
        ipv4_address: 172.22.1.7
    restart: "no"
    profiles:
      - donotstart

networks:
  password_manager:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.1.0/24
          gateway: 172.22.1.1


volumes:
  password_manager_db: {}
  maven_cache: {}

